FROM openjdk:8-slim-buster as build
COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .
COPY src src
RUN ./mvnw package

FROM openjdk:8-jre-slim-buster
COPY --from=build target/demo.jar .
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "demo.jar"]